import {
  snare,
  wow,
  applause,
  babylaugh,
  beep,
  boo,
  chaching,
  rooster,
  train,
  fart,
  partyhorn,
  // foghorn,
  // woosh,
  // trex,
  // dixiehorn,
  // hyena,
  // news,
  // ==============
  aintnobodygottimeforthat,
  boring,
  catchmeoutside,
  evillaugh,
  gibberish,
  hideyokids,
  iamtheone,
  igotabadfeeling,
  itwasatthismoment,
  missionimpossible,
  ohhellno,
  ohmygod,
  slap,
  surprisemotherfucker,
  tada,
  triggered,
  wasted,
  afewmomentslater,
  aww,
  bruh,
  cheering,
  circus,
  crickets,
  deeznuts,
  dialup,
  dreamharp,
  drumroll,
  dundundun,
  elevatormusic,
  fbi,
  golfswing,
  hahahawtf,
  heavenlymusic,
  illuminati,
  johncena,
  justdoit,
  laugh,
  meepmeep,
  nice,
  nonono,
  nope,
  nopleaseno,
  ohh,
  ok,
  recordscratch,
  runrun,
  sad,
  saywhat,
  shotsfired,
  squeak,
  toinfinity,
  waitaminute,
  wiitheme,
  garbage,
  cork,
  buzzer,
  oopsie,
  toasty,
  thuglife,
  lovemoment,
  dolphin,
  windowserror,
  lion,
  waitinggame,
  yeehaw,
  gameover,
  sheep,
  gtfo,
  terminator,
  noidea,
  knock,
} from "../Sounds";

export const Combos = [
  { name: "Party Horn", image: "🥳", sound: partyhorn, isFavorite: false },
  { name: "Applause", image: "👏", sound: applause, isFavorite: false },
  { name: "Ba Dum Tss", image: "🥁", sound: snare, isFavorite: false },
  { name: "Wow", image: "😮", sound: wow, isFavorite: false },
  { name: "$$$", image: "💸", sound: chaching, isFavorite: false },
  { name: "Rooster", image: "🐓", sound: rooster, isFavorite: false },
  { name: "Train", image: "🚂", sound: train, isFavorite: false },
  { name: "Fart", image: "💨", sound: fart, isFavorite: false },
  { name: "Boo", image: "👎", sound: boo, isFavorite: false },
  { name: "Baby Laugh", image: "👶", sound: babylaugh, isFavorite: false },
  { name: "Beep", image: "🤬", sound: beep, isFavorite: false },
  { name: "", image: "🔥", sound: "", isFavorite: false },
  { name: "", image: "👊", sound: "", isFavorite: false },
  { name: "", image: "😴", sound: "", isFavorite: false },
  { name: "", image: "👀", sound: "", isFavorite: false },
  { name: "", image: "😎", sound: "", isFavorite: false },
  { name: "", image: "😬", sound: "", isFavorite: false },
  { name: "", image: "🚀", sound: "", isFavorite: false },
  { name: "Shots Fired", image: "🧨", sound: shotsfired, isFavorite: false },
  { name: "Wait a minute", image: "🧐", sound: waitaminute, isFavorite: false },
  { name: "Crickets", image: "🦗", sound: crickets, isFavorite: false },
  { name: "Lion", image: "🦁 ", sound: lion, isFavorite: false },
  { name: "Boring", image: "🥱", sound: boring, isFavorite: false },
  { name: "Aww", image: "🥰", sound: aww, isFavorite: false },
  { name: "Deez Nuts", image: "🥜", sound: deeznuts, isFavorite: false },
  { name: "Drumroll", image: "🥁", sound: drumroll, isFavorite: false },
  { name: "Gibberish", image: "🤪", sound: gibberish, isFavorite: false },
  { name: "Hahaha WTF", image: "🤣", sound: hahahawtf, isFavorite: false },
  {
    name: "Windows Error",
    image: "🚫",
    sound: windowserror,
    isFavorite: false,
  },
  { name: "Buzzer", image: "🚨", sound: buzzer, isFavorite: false },
  { name: "Oopsie", image: "🙊", sound: oopsie, isFavorite: false },
  { name: "Oh Hell No", image: "🙅‍♂", sound: ohhellno, isFavorite: false },
  {
    name: "It was at this moment",
    image: "🙃",
    sound: itwasatthismoment,
    isFavorite: false,
  },
  { name: "Say what", image: "😳", sound: saywhat, isFavorite: false },
  { name: "Oh my god", image: "😲", sound: ohmygod, isFavorite: false },
  {
    name: "I've got a bad feeling",
    image: "😬",
    sound: igotabadfeeling,
    isFavorite: false,
  },
  { name: "Triggered", image: "😪", sound: triggered, isFavorite: false },
  { name: "Bruh", image: "😩", sound: bruh, isFavorite: false },
  { name: "Love Moment", image: "😍", sound: lovemoment, isFavorite: false },
  { name: "Evil Laugh", image: "😈", sound: evillaugh, isFavorite: false },
  {
    name: "Heavenly Music",
    image: "😇",
    sound: heavenlymusic,
    isFavorite: false,
  },
  { name: "Piece of Garbage", image: "🗑", sound: garbage, isFavorite: false },
  { name: "FBI Open Up", image: "🕵️", sound: fbi, isFavorite: false },
  {
    name: "Mission Impossible",
    image: "🕴",
    sound: missionimpossible,
    isFavorite: false,
  },
  { name: "Flashback", image: "💭", sound: dreamharp, isFavorite: true },
  { name: "Slap", image: "👋", sound: slap, isFavorite: true },
  { name: "Illuminati", image: "👁", sound: illuminati, isFavorite: true },
  { name: "Dolphin", image: "🐬", sound: dolphin, isFavorite: true },
  { name: "Golf Hit", image: "🏌", sound: golfswing, isFavorite: true },
  { name: "Run Run", image: "🏃‍♀️", sound: runrun, isFavorite: true },
  { name: "Wii Theme", image: "🎮", sound: wiitheme, isFavorite: true },
  { name: "Circus", image: "🎪", sound: circus, isFavorite: true },
  { name: "Cheering", image: "🎉", sound: cheering, isFavorite: true },
  { name: "Cork", image: "🍾", sound: cork, isFavorite: true },
  { name: "Toasty!", image: "🍞", sound: toasty, isFavorite: true },
  { name: "Nope", image: "❌", sound: nope, isFavorite: true },
  { name: "Tada", image: "✨", sound: tada, isFavorite: true },
  { name: "Sad", image: "😞", sound: sad, isFavorite: true },
  { name: "I am the one", image: "☝️", sound: iamtheone, isFavorite: true },
  {
    name: "Ain't nobody got time",
    image: "⏳",
    sound: aintnobodygottimeforthat,
    isFavorite: false,
  },
  { name: "GTFO", image: "🖕", sound: gtfo, isFavorite: false },
  { name: "Knock Knock", image: "🚪", sound: knock, isFavorite: false },
  { name: "Game Over", image: "👾", sound: gameover, isFavorite: false },
  { name: "Sheep", image: "🐑", sound: sheep, isFavorite: false },
  {
    name: "I have absolutely no idea",
    image: "",
    sound: noidea,
    isFavorite: false,
  },
  { name: "I'll be back", image: "", sound: terminator, isFavorite: false },
  { name: "Waiting Game", image: "⏱", sound: waitinggame, isFavorite: false },
  { name: "Wasted", image: "☠️", sound: wasted, isFavorite: false },
  { name: "John Cena", image: "✋", sound: johncena, isFavorite: false },
  { name: "Thug Life", image: "🕶", sound: thuglife, isFavorite: false },
  { name: "Meep Meep", image: "", sound: meepmeep, isFavorite: false },
  { name: "Just Do It", image: "💪", sound: justdoit, isFavorite: false },
  { name: "Squeak", image: "", sound: squeak, isFavorite: false },
  { name: "Laugh", image: "", sound: laugh, isFavorite: false },
  { name: "Nice", image: "😏", sound: nice, isFavorite: false },
  {
    name: "Surprise Motherf*cker",
    image: "",
    sound: surprisemotherfucker,
    isFavorite: false,
  },
  { name: "No no no", image: "", sound: nonono, isFavorite: false },
  {
    name: "A few moments later",
    image: "",
    sound: afewmomentslater,
    isFavorite: false,
  },
  {
    name: "Too Infinity & Beyond",
    image: "",
    sound: toinfinity,
    isFavorite: false,
  },
  { name: "No God No", image: "", sound: nopleaseno, isFavorite: false },
  { name: "Hide yo' Kids", image: "", sound: hideyokids, isFavorite: false },
  { name: "Ohhh", image: "", sound: ohh, isFavorite: false },
  {
    name: "Catch me outside",
    image: "",
    sound: catchmeoutside,
    isFavorite: false,
  },
  { name: "Yeehaw", image: "🤠", sound: yeehaw, isFavorite: false },
  { name: "Dun dun dun", image: "", sound: dundundun, isFavorite: false },
  { name: "Dial Up", image: "", sound: dialup, isFavorite: false },
  {
    name: "Elevator Music",
    image: "",
    sound: elevatormusic,
    isFavorite: false,
  },
  {
    name: "Record Scratch",
    image: "",
    sound: recordscratch,
    isFavorite: false,
  },
  { name: "Ok", image: "", sound: ok, isFavorite: false },
];
