import {
  snare,
  wow,
  applause,
  babylaugh,
  beep,
  boo,
  chaching,
  rooster,
  train,
  fart,
  partyhorn,
  // foghorn,
  // woosh,
  trex,
  // dixiehorn,
  // hyena,
  // news,
  // ==============
  aintnobodygottimeforthat,
  boring,
  catchmeoutside,
  evillaugh,
  gibberish,
  hideyokids,
  iamtheone,
  igotabadfeeling,
  itwasatthismoment,
  missionimpossible,
  ohhellno,
  ohmygod,
  slap,
  surprisemotherfucker,
  tada,
  triggered,
  wasted,
  afewmomentslater,
  aww,
  bruh,
  cheering,
  circus,
  crickets,
  deeznuts,
  dialup,
  dreamharp,
  drumroll,
  dundundun,
  elevatormusic,
  fbi,
  golfswing,
  hahahawtf,
  heavenlymusic,
  illuminati,
  johncena,
  justdoit,
  laugh,
  meepmeep,
  nice,
  nonono,
  nope,
  nopleaseno,
  ohh,
  ok,
  recordscratch,
  runrun,
  sad,
  saywhat,
  shotsfired,
  squeak,
  toinfinity,
  waitaminute,
  wiitheme,
  garbage,
  cork,
  buzzer,
  oopsie,
  toasty,
  thuglife,
  lovemoment,
  dolphin,
  windowserror,
  lion,
  waitinggame,
  yeehaw,
  gameover,
  sheep,
  gtfo,
  terminator,
  noidea,
  knock,
  romantic,
  wegothim,
  coin,
  developers,
  youplayedyourself,
  anotherone,
  meanwhile,
  twohourslater,
  oneeternity,
  gong,
  twokyears,
} from "../Sounds";

export const Combos = [
  {
    name: "Party Horn",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/face-with-party-horn-and-party-hat_1f973.png",
    sound: partyhorn,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Applause",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/clapping-hands-sign_1f44f.png",
    sound: applause,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Ba Dum Tss",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/drum-with-drumsticks_1f941.png",
    sound: snare,
    plan: "free",
    isFavorite: false,
  },
  { name: "Wow", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/face-with-open-mouth_1f62e.png", sound: wow, plan: "free", isFavorite: false },
  {
    name: "$$$",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/money-with-wings_1f4b8.png",
    sound: chaching,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Rooster",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/rooster_1f413.png",
    sound: rooster,
    plan: "free",
    isFavorite: false,
  },
  { name: "Train", image: "https://unicodey.com/emoji-data/img-apple-64/1f682.png", sound: train, plan: "free", isFavorite: false },
  { name: "Fart", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/dash-symbol_1f4a8.png", sound: fart, plan: "free", isFavorite: false },
  { name: "Boo", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/thumbs-down-sign_1f44e.png", sound: boo, plan: "free", isFavorite: false },
  {
    name: "Baby Laugh",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/baby_1f476.png",
    sound: babylaugh,
    plan: "free",
    isFavorite: false,
  },
  { name: "Beep", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/serious-face-with-symbols-covering-mouth_1f92c.png", sound: beep, plan: "free", isFavorite: false },
  { name: "T-Rex", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/t-rex_1f996.png", sound: trex, plan: "free", isFavorite: false },
  // { name: "", image: "🔥", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "👊", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "😴", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "👀", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "😎", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "😬", sound: "", plan: "free", isFavorite: false },
  {
    name: "Shots Fired",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/firecracker_1f9e8.png",
    sound: shotsfired,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Wait a minute",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/face-with-monocle_1f9d0.png",
    sound: waitaminute,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Crickets",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/cricket_1f997.png",
    sound: crickets,
    plan: "free",
    isFavorite: false,
  },
  { name: "Lion", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/lion-face_1f981.png", sound: lion, plan: "free", isFavorite: false },
  {
    name: "Boring",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/yawning-face_1f971.png",
    sound: boring,
    plan: "free",
    isFavorite: false,
  },
  { name: "Aww", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/smiling-face-with-smiling-eyes-and-three-hearts_1f970.png", sound: aww, plan: "free", isFavorite: false },
  {
    name: "Deez Nuts",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/peanuts_1f95c.png",
    sound: deeznuts,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Drumroll",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/drum-with-drumsticks_1f941.png",
    sound: drumroll,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Gibberish",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/grinning-face-with-one-large-and-one-small-eye_1f92a.png",
    sound: gibberish,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Hahaha WTF",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/rolling-on-the-floor-laughing_1f923.png",
    sound: hahahawtf,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Windows Error",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/no-entry-sign_1f6ab.png",
    sound: windowserror,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Buzzer",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/police-cars-revolving-light_1f6a8.png",
    sound: buzzer,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Oopsie",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/speak-no-evil-monkey_1f64a.png",
    sound: oopsie,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Oh Hell No",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/man-gesturing-not-ok_1f645-200d-2642-fe0f.png",
    sound: ohhellno,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "It was at this moment",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/upside-down-face_1f643.png",
    sound: itwasatthismoment,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Say what",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/flushed-face_1f633.png",
    sound: saywhat,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Oh my god",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/astonished-face_1f632.png",
    sound: ohmygod,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "I've got a bad feeling",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/grimacing-face_1f62c.png",
    sound: igotabadfeeling,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Triggered",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sleepy-face_1f62a.png",
    sound: triggered,
    plan: "free",
    isFavorite: false,
  },
  { name: "Bruh", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/weary-face_1f629.png", sound: bruh, plan: "free", isFavorite: false },
  {
    name: "Love Moment",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/smiling-face-with-heart-shaped-eyes_1f60d.png",
    sound: lovemoment,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Evil Laugh",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/smiling-face-with-horns_1f608.png",
    sound: evillaugh,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Heavenly Music",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/smiling-face-with-halo_1f607.png",
    sound: heavenlymusic,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Piece of Garbage",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/wastebasket_1f5d1.png",
    sound: garbage,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "FBI Open Up",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sleuth-or-spy_1f575.png",
    sound: fbi,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Mission Impossible",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/man-in-business-suit-levitating_1f574.png",
    sound: missionimpossible,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Flashback",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/thought-balloon_1f4ad.png",
    sound: dreamharp,
    plan: "free",
    isFavorite: true,
  },
  { name: "Slap", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/waving-hand-sign_1f44b.png", sound: slap, plan: "free", isFavorite: true },
  {
    name: "Illuminati",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/eye_1f441.png",
    sound: illuminati,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Dolphin",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/dolphin_1f42c.png",
    sound: dolphin,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Golf Hit",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/golfer_1f3cc.png",
    sound: golfswing,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Run Run",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/woman-running_1f3c3-200d-2640-fe0f.png",
    sound: runrun,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Wii Theme",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/video-game_1f3ae.png",
    sound: wiitheme,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Circus",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/circus-tent_1f3aa.png",
    sound: circus,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Cheering",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/party-popper_1f389.png",
    sound: cheering,
    plan: "free",
    isFavorite: true,
  },
  { name: "Cork", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/bottle-with-popping-cork_1f37e.png", sound: cork, plan: "free", isFavorite: true },
  {
    name: "Toasty!",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/bread_1f35e.png",
    sound: toasty,
    plan: "free",
    isFavorite: true,
  },
  { name: "Nope", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/cross-mark_274c.png", sound: nope, plan: "free", isFavorite: true },
  { name: "Tada", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sparkles_2728.png", sound: tada, plan: "free", isFavorite: true },
  { name: "Sad", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/disappointed-face_1f61e.png", sound: sad, plan: "free", isFavorite: true },
  {
    name: "I am the one",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/white-up-pointing-index_261d.png",
    sound: iamtheone,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Ain't nobody got time",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/hourglass-with-flowing-sand_23f3.png",
    sound: aintnobodygottimeforthat,
    plan: "free",
    isFavorite: false,
  },
  { name: "GTFO", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/reversed-hand-with-middle-finger-extended_1f595.png", sound: gtfo, plan: "free", isFavorite: false },
  {
    name: "Knock Knock",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/door_1f6aa.png",
    sound: knock,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Game Over",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/alien-monster_1f47e.png",
    sound: gameover,
    plan: "free",
    isFavorite: false,
  },
  { name: "Sheep", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sheep_1f411.png", sound: sheep, plan: "free", isFavorite: false },
  {
    name: "I have absolutely no idea",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/man-shrugging_1f937-200d-2642-fe0f.png",
    sound: noidea,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "I'll be back",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/mechanical-arm_1f9be.png",
    sound: terminator,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Waiting Game",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/stopwatch_23f1.png",
    sound: waitinggame,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Wasted",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/skull-and-crossbones_2620.png",
    sound: wasted,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "John Cena",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/raised-hand_270b.png",
    sound: johncena,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Thug Life",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/dark-sunglasses_1f576.png",
    sound: thuglife,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Meep Meep",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/parrot_1f99c.png",
    sound: meepmeep,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Just Do It",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/flexed-biceps_1f4aa.png",
    sound: justdoit,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Squeak",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/front-facing-baby-chick_1f425.png",
    sound: squeak,
    plan: "free",
    isFavorite: false,
  },
  { name: "Laugh", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/smiling-face-with-open-mouth-and-tightly-closed-eyes_1f606.png", sound: laugh, plan: "free", isFavorite: false },
  { name: "Nice", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/smirking-face_1f60f.png", sound: nice, plan: "free", isFavorite: false },
  {
    name: "Surprise Motherf*cker",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/smiling-face-with-horns_1f608.png",
    sound: surprisemotherfucker,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "No no no",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/face-with-tears-of-joy_1f602.png",
    sound: nonono,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Too Infinity & Beyond",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/rocket_1f680.png",
    sound: toinfinity,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "No God No",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/man-gesturing-not-ok_1f645-200d-2642-fe0f.png",
    sound: nopleaseno,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Hide yo' Kids",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/children-crossing_1f6b8.png",
    sound: hideyokids,
    plan: "free",
    isFavorite: false,
  },
  { name: "Ohhh", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/shocked-face-with-exploding-head_1f92f.png", sound: ohh, plan: "free", isFavorite: false },
  {
    name: "Cash me outside",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/money-with-wings_1f4b8.png",
    sound: catchmeoutside,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Yeehaw",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/face-with-cowboy-hat_1f920.png",
    sound: yeehaw,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Dun dun dun",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/weary-cat-face_1f640.png",
    sound: dundundun,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Dial Up",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/fax-machine_1f4e0.png",
    sound: dialup,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Elevator Music",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/emojipedia/240/elevator_1f6d7.png",
    sound: elevatormusic,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Record Scratch",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/videocassette_1f4fc.png",
    sound: recordscratch,
    plan: "free",
    isFavorite: false,
  },
  { name: "Ok", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/squared-ok_1f197.png", sound: ok, plan: "free", isFavorite: false },
  {
    name: "Romantic",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/two-hearts_1f495.png",
    sound: romantic,
    plan: "free",
    isFavorite: false,
  },
  { name: "Gong", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/nazar-amulet_1f9ff.png", sound: gong, plan: "free", isFavorite: false },
  {
    name: "We Got Him",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/person-raising-both-hands-in-celebration_1f64c.png",
    sound: wegothim,
    plan: "free",
    isFavorite: false,
  },
  { name: "Coin", image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/money-bag_1f4b0.png", sound: coin, plan: "free", isFavorite: false },
  {
    name: "Developers",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/female-technologist_1f469-200d-1f4bb.png",
    sound: developers,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Played Yourself",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/man-facepalming_1f926-200d-2642-fe0f.png",
    sound: youplayedyourself,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Another One",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/white-up-pointing-backhand-index_1f446.png",
    sound: anotherone,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "A few moments later",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sponge_1f9fd.png",
    image2: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/jeans_1f456.png",
    sound: afewmomentslater,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Meanwhile",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sponge_1f9fd.png",
    image2: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/jeans_1f456.png",
    sound: meanwhile,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Two Hours Later",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sponge_1f9fd.png",
    image2: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/jeans_1f456.png",
    sound: twohourslater,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "2k Year Later",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sponge_1f9fd.png",
    image2: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/jeans_1f456.png",
    sound: twokyears,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "One Eternity",
    image: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/sponge_1f9fd.png",
    image2: "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/jeans_1f456.png",
    sound: oneeternity,
    plan: "free",
    isFavorite: false,
  },
];
