import {
  snare,
  wow,
  applause,
  babylaugh,
  beep,
  boo,
  chaching,
  rooster,
  train,
  fart,
  partyhorn,
  // foghorn,
  // woosh,
  trex,
  // dixiehorn,
  // hyena,
  // news,
  // ==============
  aintnobodygottimeforthat,
  boring,
  catchmeoutside,
  evillaugh,
  gibberish,
  hideyokids,
  iamtheone,
  igotabadfeeling,
  itwasatthismoment,
  missionimpossible,
  ohhellno,
  ohmygod,
  slap,
  surprisemotherfucker,
  tada,
  triggered,
  wasted,
  afewmomentslater,
  aww,
  bruh,
  cheering,
  circus,
  crickets,
  deeznuts,
  dialup,
  dreamharp,
  drumroll,
  dundundun,
  elevatormusic,
  fbi,
  golfswing,
  hahahawtf,
  heavenlymusic,
  illuminati,
  johncena,
  justdoit,
  laugh,
  meepmeep,
  nice,
  nonono,
  nope,
  nopleaseno,
  ohh,
  ok,
  recordscratch,
  runrun,
  sad,
  saywhat,
  shotsfired,
  squeak,
  toinfinity,
  waitaminute,
  wiitheme,
  garbage,
  cork,
  buzzer,
  oopsie,
  toasty,
  thuglife,
  lovemoment,
  dolphin,
  windowserror,
  lion,
  waitinggame,
  yeehaw,
  gameover,
  sheep,
  gtfo,
  terminator,
  noidea,
  knock,
  romantic,
  wegothim,
  coin,
  developers,
  youplayedyourself,
  anotherone,
  meanwhile,
  twohourslater,
  oneeternity,
  gong,
  twokyears,
} from "../Sounds";

export const Combos = [
  {
    name: "Party Horn",
    image: "🥳",
    sound: partyhorn,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Applause",
    image: "👏",
    sound: applause,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Ba Dum Tss",
    image: "🥁",
    sound: snare,
    plan: "free",
    isFavorite: false,
  },
  { name: "Wow", image: "😮", sound: wow, plan: "free", isFavorite: false },
  {
    name: "$$$",
    image: "💸",
    sound: chaching,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Rooster",
    image: "🐓",
    sound: rooster,
    plan: "free",
    isFavorite: false,
  },
  { name: "Train", image: "🚂", sound: train, plan: "free", isFavorite: false },
  { name: "Fart", image: "💨", sound: fart, plan: "free", isFavorite: false },
  { name: "Boo", image: "👎", sound: boo, plan: "free", isFavorite: false },
  {
    name: "Baby Laugh",
    image: "👶",
    sound: babylaugh,
    plan: "free",
    isFavorite: false,
  },
  { name: "Beep", image: "🤬", sound: beep, plan: "free", isFavorite: false },
  { name: "T-Rex", image: "🦖", sound: trex, plan: "free", isFavorite: false },
  // { name: "", image: "🔥", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "👊", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "😴", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "👀", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "😎", sound: "", plan: "free", isFavorite: false },
  // { name: "", image: "😬", sound: "", plan: "free", isFavorite: false },
  {
    name: "Shots Fired",
    image: "🧨",
    sound: shotsfired,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Wait a minute",
    image: "🧐",
    sound: waitaminute,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Crickets",
    image: "🦗",
    sound: crickets,
    plan: "free",
    isFavorite: false,
  },
  { name: "Lion", image: "🦁 ", sound: lion, plan: "free", isFavorite: false },
  {
    name: "Boring",
    image: "🥱",
    sound: boring,
    plan: "free",
    isFavorite: false,
  },
  { name: "Aww", image: "🥰", sound: aww, plan: "free", isFavorite: false },
  {
    name: "Deez Nuts",
    image: "🥜",
    sound: deeznuts,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Drumroll",
    image: "🥁",
    sound: drumroll,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Gibberish",
    image: "🤪",
    sound: gibberish,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Hahaha WTF",
    image: "🤣",
    sound: hahahawtf,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Windows Error",
    image: "🚫",
    sound: windowserror,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Buzzer",
    image: "🚨",
    sound: buzzer,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Oopsie",
    image: "🙊",
    sound: oopsie,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Oh Hell No",
    image: "🙅‍♂",
    sound: ohhellno,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "It was at this moment",
    image: "🙃",
    sound: itwasatthismoment,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Say what",
    image: "😳",
    sound: saywhat,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Oh my god",
    image: "😲",
    sound: ohmygod,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "I've got a bad feeling",
    image: "😬",
    sound: igotabadfeeling,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Triggered",
    image: "😪",
    sound: triggered,
    plan: "free",
    isFavorite: false,
  },
  { name: "Bruh", image: "😩", sound: bruh, plan: "free", isFavorite: false },
  {
    name: "Love Moment",
    image: "😍",
    sound: lovemoment,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Evil Laugh",
    image: "😈",
    sound: evillaugh,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Heavenly Music",
    image: "😇",
    sound: heavenlymusic,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Piece of Garbage",
    image: "🗑",
    sound: garbage,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "FBI Open Up",
    image: "🕵️",
    sound: fbi,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Mission Impossible",
    image: "🕴",
    sound: missionimpossible,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Flashback",
    image: "💭",
    sound: dreamharp,
    plan: "free",
    isFavorite: true,
  },
  { name: "Slap", image: "👋", sound: slap, plan: "free", isFavorite: true },
  {
    name: "Illuminati",
    image: "👁",
    sound: illuminati,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Dolphin",
    image: "🐬",
    sound: dolphin,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Golf Hit",
    image: "🏌",
    sound: golfswing,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Run Run",
    image: "🏃‍♀️",
    sound: runrun,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Wii Theme",
    image: "🎮",
    sound: wiitheme,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Circus",
    image: "🎪",
    sound: circus,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Cheering",
    image: "🎉",
    sound: cheering,
    plan: "free",
    isFavorite: true,
  },
  { name: "Cork", image: "🍾", sound: cork, plan: "free", isFavorite: true },
  {
    name: "Toasty!",
    image: "🍞",
    sound: toasty,
    plan: "free",
    isFavorite: true,
  },
  { name: "Nope", image: "❌", sound: nope, plan: "free", isFavorite: true },
  { name: "Tada", image: "✨", sound: tada, plan: "free", isFavorite: true },
  { name: "Sad", image: "😞", sound: sad, plan: "free", isFavorite: true },
  {
    name: "I am the one",
    image: "☝️",
    sound: iamtheone,
    plan: "free",
    isFavorite: true,
  },
  {
    name: "Ain't nobody got time",
    image: "⏳",
    sound: aintnobodygottimeforthat,
    plan: "free",
    isFavorite: false,
  },
  { name: "GTFO", image: "🖕", sound: gtfo, plan: "free", isFavorite: false },
  {
    name: "Knock Knock",
    image: "🚪",
    sound: knock,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Game Over",
    image: "👾",
    sound: gameover,
    plan: "free",
    isFavorite: false,
  },
  { name: "Sheep", image: "🐑", sound: sheep, plan: "free", isFavorite: false },
  {
    name: "I have absolutely no idea",
    image: "🤷‍♂️",
    sound: noidea,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "I'll be back",
    image: "🦾",
    sound: terminator,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Waiting Game",
    image: "⏱",
    sound: waitinggame,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Wasted",
    image: "☠️",
    sound: wasted,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "John Cena",
    image: "✋",
    sound: johncena,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Thug Life",
    image: "🕶",
    sound: thuglife,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Meep Meep",
    image: "🦜",
    sound: meepmeep,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Just Do It",
    image: "💪",
    sound: justdoit,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Squeak",
    image: "🐥",
    sound: squeak,
    plan: "free",
    isFavorite: false,
  },
  { name: "Laugh", image: "😆", sound: laugh, plan: "free", isFavorite: false },
  { name: "Nice", image: "😏", sound: nice, plan: "free", isFavorite: false },
  {
    name: "Surprise Motherf*cker",
    image: "😈",
    sound: surprisemotherfucker,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "No no no",
    image: "😂",
    sound: nonono,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Too Infinity & Beyond",
    image: "🚀",
    sound: toinfinity,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "No God No",
    image: "🙅‍♂️",
    sound: nopleaseno,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Hide yo' Kids",
    image: "🚸",
    sound: hideyokids,
    plan: "free",
    isFavorite: false,
  },
  { name: "Ohhh", image: "🤯", sound: ohh, plan: "free", isFavorite: false },
  {
    name: "Cash me outside",
    image: "💸",
    sound: catchmeoutside,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Yeehaw",
    image: "🤠",
    sound: yeehaw,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Dun dun dun",
    image: "🙀",
    sound: dundundun,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Dial Up",
    image: "📠",
    sound: dialup,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Elevator Music",
    image: "📻",
    sound: elevatormusic,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Record Scratch",
    image: "📼",
    sound: recordscratch,
    plan: "free",
    isFavorite: false,
  },
  { name: "Ok", image: "🆗", sound: ok, plan: "free", isFavorite: false },
  {
    name: "Romantic",
    image: "💕",
    sound: romantic,
    plan: "free",
    isFavorite: false,
  },
  { name: "Gong", image: "🧿", sound: gong, plan: "free", isFavorite: false },
  {
    name: "We Got Him",
    image: "🙌",
    sound: wegothim,
    plan: "free",
    isFavorite: false,
  },
  { name: "Coin", image: "💰", sound: coin, plan: "free", isFavorite: false },
  {
    name: "Developers",
    image: "👩‍💻",
    sound: developers,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Played Yourself",
    image: "🤦‍♂️",
    sound: youplayedyourself,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Another One",
    image: "👆",
    sound: anotherone,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "A few moments later",
    image: "🧽👖",
    sound: afewmomentslater,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Meanwhile",
    image: "🧽👖",
    sound: meanwhile,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "Two Hours Later",
    image: "🧽👖",
    sound: twohourslater,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "2k Year Later",
    image: "🧽👖",
    sound: twokyears,
    plan: "free",
    isFavorite: false,
  },
  {
    name: "One Eternity",
    image: "🧽👖",
    sound: oneeternity,
    plan: "free",
    isFavorite: false,
  },
];
